"""Initial schema."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
revision="0001";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.execute("CREATE EXTENSION IF NOT EXISTS vector")
 op.create_table("tenants",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("slug",sa.String(80),nullable=False,unique=True),sa.Column("name",sa.String(200),nullable=False),sa.Column("active",sa.Boolean(),server_default=sa.true(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("permissions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("code",sa.String(100),unique=True,nullable=False),sa.Column("description",sa.String(250),nullable=False))
 op.create_table("users",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id",ondelete="CASCADE"),nullable=False),sa.Column("email",sa.String(320),nullable=False),sa.Column("password_hash",sa.String(500),nullable=False),sa.Column("active",sa.Boolean(),server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("tenant_id","email",name="uq_users_tenant_email"))
 op.create_table("roles",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(80),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("tenant_id","name",name="uq_roles_tenant_name"))
 op.create_table("user_roles",sa.Column("user_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),sa.Column("role_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("roles.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("role_permissions",sa.Column("role_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("roles.id",ondelete="CASCADE"),primary_key=True),sa.Column("permission_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("permissions.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("documents",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(250),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("metadata",postgresql.JSONB(),server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("embedding",Vector(1536)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("audit_events",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("tenant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tenants.id",ondelete="RESTRICT"),nullable=False),sa.Column("actor_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(120),nullable=False),sa.Column("resource",sa.String(250),nullable=False),sa.Column("details",postgresql.JSONB(),server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 for table in ("users","roles","documents","audit_events"):op.create_index(f"ix_{table}_tenant_id",table,["tenant_id"])
def downgrade():
 for table in ("audit_events","documents","role_permissions","user_roles","roles","users","permissions","tenants"):op.drop_table(table)
